### ISSUE TITLE
Building a Login page(includes Authentication).

### ISSUE THREAD

**Issue by jashu100** [the-alpha-team03/alpha-project#5]
Develop a Login page that enables a user to signup and Login.
1.Users should be able to register with the required information including name, age, mobile number, DOB, address, email and password.
2.Proper error messages should be displayed if registration fails due to invalid input.
3.Registered users should be able to sign in using valid credentials.

**Comment by jashu100** [comment]
can u please update your comment on this task progress

**Comment by jashu100** [comment]
I have understood the task. I will complete it by tomorrow EOD.

**Comment by pullurilikith** [comment]
I have understood the task. I will complete it by tomorrow EOD.

**Comment by jashu100** [comment]
code merged so closing the task.
