### ISSUE TITLE
Development of login page Functionality (Authentication)- Backend 

### ISSUE THREAD

**Issue by jashu100** [the-alpha-team03/alpha-project#6]
Code Development for login functionality.
1st case :
1. The first request if a backend receives signup(user registration) request from a frontend then the backend logic should check that all the requirements are fulfilled and if satisfies then the user details should be saved in database for future validations.
2. If the request not fulfills all the necessary requirements then appropriate error message should be thrown.
2nd case :
1.when backend receives a request from front end for a user to login with his credentials the backend logic should connect to database and verify whether a user entered correct credentials.
2.If the user enters correct details then it should allow the user to be able to login or throw a error message for 
Example : invalid credentials.

**Comment by balineni5** [comment]
Understood the requirements and started code development, 50% code development completed , will complete the remaining functionality will test and push the code by EOD.

**Comment by jashu100** [comment]
Understood the requirements and started code development, 50% code development completed , will complete the remaining functionality will test and push the code by EOD.

**Comment by jashu100** [comment]
Code development completed and pull request merged.closing the task
