### ISSUE TITLE
Development of Job Categories Functionality  - Frontend

### ISSUE THREAD

**Issue by jashu100** [the-alpha-team03/alpha-project#7]
Create a Categories Page that helps the user to select criteria as per his interest. 
The developed page should fulfill these functionality
1. Enable job search by job title, location, industry, salary range, and keyword.
2. Implement filters for refining search results by job type.

**Comment by jashu100** [comment]
can u please update your comment on present working task.

**Comment by balineni5** [comment]
understood the requirement and started the code development, will raise the PR by EOD.

**Comment by jashu100** [comment]
code merged so closing this jira
